// Generated by ReScript, PLEASE EDIT WITH CARE


function calcInterestRate(percentInterest) {
  return percentInterest / 100.0;
}

function rateDivide12(rate) {
  return rate / 12.0;
}

function getRest(rate12, numMonths) {
  return rate12 / (1.0 - Math.pow(1.0 + rate12, -numMonths));
}

function finalCalc(rest, principal) {
  return principal * rest;
}

function monthlyPayment(principal, percentInterest, numMonths) {
  return principal * getRest(percentInterest / 100.0 / 12.0, numMonths);
}

function totalRepaymentAmount(monthlyPayment, numMonths) {
  return monthlyPayment * numMonths;
}

function totalInterestAmount(totalRepay, principal) {
  return totalRepay - principal;
}

export {
  calcInterestRate ,
  rateDivide12 ,
  getRest ,
  finalCalc ,
  monthlyPayment ,
  totalRepaymentAmount ,
  totalInterestAmount ,
  
}
/* No side effect */
