// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Conversions from "../../../helpers/conversions/Conversions.bs.js";
import * as CarLoanCalculator from "../../../helpers/calculators/CarLoanCalculator.bs.js";

var now = new Date();

console.log("DATE ---> ", now);

function CarLoan(Props) {
  var match = React.useState(function () {
        return 0.0;
      });
  var setPrincipal = match[1];
  var principal = match[0];
  var match$1 = React.useState(function () {
        return 0.0;
      });
  var setPercentInterest = match$1[1];
  var percentInterest = match$1[0];
  var match$2 = React.useState(function () {
        return 0.0;
      });
  var setNumMonths = match$2[1];
  var numMonths = match$2[0];
  var match$3 = React.useState(function () {
        return 0.00;
      });
  var setPayment = match$3[1];
  var match$4 = React.useState(function () {
        return 0.00;
      });
  var setTotalPayments = match$4[1];
  var match$5 = React.useState(function () {
        return 0.00;
      });
  var setTotalInterest = match$5[1];
  var updateForm = function (e, loanType) {
    var val = e.currentTarget.value;
    switch (loanType) {
      case /* Principal */0 :
          return Curry._1(setPrincipal, val);
      case /* Interest */1 :
          return Curry._1(setPercentInterest, val);
      case /* Months */2 :
          return Curry._1(setNumMonths, val);
      
    }
  };
  var calculateMonthlyPayment = function (param) {
    var p = CarLoanCalculator.monthlyPayment(principal, percentInterest, numMonths);
    var totPay = CarLoanCalculator.totalRepaymentAmount(p, numMonths);
    var totInt = CarLoanCalculator.totalInterestAmount(totPay, principal);
    Curry._1(setPayment, (function (param) {
            return p;
          }));
    Curry._1(setTotalInterest, (function (param) {
            return totInt;
          }));
    return Curry._1(setTotalPayments, (function (param) {
                  return totPay;
                }));
  };
  return React.createElement("div", undefined, React.createElement("p", undefined, "Principal"), React.createElement("input", {
                  type: "text",
                  value: String(principal),
                  onChange: (function (e) {
                      return updateForm(e, /* Principal */0);
                    })
                }), React.createElement("p", undefined, "Percent Interest"), React.createElement("input", {
                  type: "text",
                  value: String(percentInterest),
                  onChange: (function (e) {
                      return updateForm(e, /* Interest */1);
                    })
                }), React.createElement("p", undefined, "Total Number of Months"), React.createElement("input", {
                  type: "text",
                  value: String(numMonths),
                  onChange: (function (e) {
                      return updateForm(e, /* Months */2);
                    })
                }), React.createElement("button", {
                  onClick: calculateMonthlyPayment
                }, "Get Monthly Payment"), React.createElement("h3", undefined, "Monthly Payment"), React.createElement("h2", undefined, Conversions.asCurrency(match$3[0])), React.createElement("h3", undefined, "Total Payments"), React.createElement("h2", undefined, Conversions.asCurrency(match$4[0])), React.createElement("h3", undefined, "Total Interest"), React.createElement("h2", undefined, Conversions.asCurrency(match$5[0])));
}

var make = CarLoan;

export {
  now ,
  make ,
  
}
/* now Not a pure module */
