// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as CarLoan from "./components/loans/CarLoan/CarLoan.bs.js";
import ReactSvg from "./assets/react.svg";

import './App.css'
;

var reactLogo = ReactSvg;

function App(Props) {
  return React.createElement("div", {
              className: "App"
            }, React.createElement(CarLoan.make, {}));
}

var make = App;

export {
  reactLogo ,
  make ,
  
}
/*  Not a pure module */
